---
title: "Assignment"
subtitle: "Online presentation"
output: github_document
---

## Links

Coming soon.

## Overview

You will create a presentation in which you analyze the statistical methods used in some published paper. 
This presentation must be hosted on GitHub and in HTML format using RMarkdown. 

**Presentation due date**: 04/14  
**Comments due date**: 04/21  

## Requirements

- Find an article with interesting stats. 
- Get approval for the article from the professor
- Briefly summarize the main points/research questions
- Scrutinize their methods
	- Explanation of analysis
		- What did they do?
		- How did they do it?
		- Why did they do it?
	- Appropriateness/novelty of analysis
		- Given what you know/what you have previously read, was this the best 
		analysis? 
		- Did they do something you haven't seen before? What? Why? How?
	- Presentation of results
		- Did they properly/accurately explain their results?
		- Did they properly/accurately interpret their findings?
		- Did they use tables/graphs? Did the tables/graphs facilitate 
		the interpretation of the results?
- Briefly describe why/what you liked or disliked about their analysis

## Details

- Your presentation must be an HTML presentation written in RMarkdown. 
- Your presentation must be contained in a public repo on GitHub and converted to a website using GitHub Pages.
- When you have finished...
	- Add a folder to your personal dropbox in `programming_assignments` called `online_presentation`
	- Create a README.md file that includes a link to your HTML presentation
	- Create a pull request to push your changes to the programming_assignments repo
	- Read the presentations of two other students and leave a brief comment in their repo (1 paragraph min., under issues)

## Evaluation

| Component                             | Value |
| :------------------------------------ | ----: |
| Summary of main points of article     | 5     |
| Explanation of analysis               | 8     |
| Assessment of appropriateness/novelty | 8     |
| Assessment of presentation of results | 4     |
| Create html presentation              | 1     |
| Successfully submit pull request      | 4     |
| Peer evaluation/comment 1             | 10    |
| Peer evaluation/comment 2             | 10    |
| --                                    |       |
| **Total**                             | 50    |

</br></br></br>


